name: Deploy Otimizado to Locaweb

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v4

      - name: 🧹 Preparar arquivos para deploy (sem vendor)
        run: |
          echo "🗂️ Removendo arquivos desnecessários para deploy..."

          # Remover pastas e arquivos que não devem ir para produção
          rm -rf .git
          rm -rf .github
          rm -rf tests
          rm -rf node_modules
          rm -rf vendor  # ✅ PRINCIPAL: Remover pasta vendor

          # Remover arquivos de desenvolvimento
          rm -f .env.example
          rm -f README.md
          rm -f .gitignore
          rm -f composer.json
          rm -f composer.lock
          rm -f phpunit.xml
          rm -f package.json
          rm -f package-lock.json
          rm -f yarn.lock

          # Remover arquivos de debug/teste
          rm -f debug-*.php
          rm -f test_*.php
          rm -f check_*.php

          # Criar estruturas necessárias se não existirem
          mkdir -p storage/logs
          mkdir -p storage/cache
          mkdir -p storage/uploads
          chmod -R 755 storage 2>/dev/null || true

          echo "📋 Arquivos que serão enviados:"
          find . -type f -name "*.php" | wc -l
          echo "arquivos PHP encontrados"

      - name: 📊 Estatísticas do deploy
        run: |
          echo "📈 Estatísticas do deploy:"
          echo "Total de arquivos: $(find . -type f | wc -l)"
          echo "Arquivos PHP: $(find . -type f -name "*.php" | wc -l)"
          echo "Arquivos CSS: $(find . -type f -name "*.css" | wc -l)"
          echo "Arquivos JS: $(find . -type f -name "*.js" | wc -l)"
          echo "Tamanho total: $(du -sh . | cut -f1)"

      - name: 🚀 Deploy via FTP (Otimizado)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.eagletelecom2.hospedagemdesites.ws
          username: eagletelecom2
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/sistema-callboard/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/.env
            **/README.md
            **/.github/**
            **/composer.json
            **/composer.lock
            **/phpunit.xml
            **/package.json
            **/package-lock.json
            **/yarn.lock
            **/.gitignore
            **/debug-*.php
            **/test_*.php
            **/check_*.php
            **/.DS_Store
            **/Thumbs.db
            **/*.tmp
            **/*.log

      - name: ✅ Deploy concluído
        run: |
          echo "🎉 Deploy realizado com sucesso!"
          echo "🌐 Site: https://callboard.eagletelecom.com.br/"
          echo "⚡ Deploy otimizado - apenas código próprio enviado"
          echo "📦 Pasta vendor excluída do deploy"
